### PR TITLE
Melodic Pattern Search + Highlighting features (& some refactoring)

### LINKED ISSUE #20: Melodic pattern search
Types of queries: 
- SQUARE NOTATION: assign letters to each pitch and ask for a specific series of pitches, e.g. C, D, E, F, G, A, B, c, d, e, f, g, a, b.
- AQUITANIAN NOTATION:
  - if I want to search for a melodic contour and specify just the general intervals (e.g. a second, a third, etc. but without saying if they are major or minor, or if the tone is a whole tone or a semitone), I would just use numbers and their relative distance up or down compared to the previous note using plus “+” and minus “-” followed by a space, the first element is always “X” (followed by a space) to represent a random point of departure, e.g. X +3 +1 -1 -1 +3 0.  (Maximum interval: +8 or -8). In this case the results will bring all the occurrences of that series of intervals regardless of the neume shapes employed.

- The comma signals the neume boundaries; it can be used after each number to signify a series of puncta, e.g, X, +3, +1, -1, -1,+3, 0 . Or it can be used after some numbers to signify pes (“X+1,”), clivis (“X-1,”), torculus (“X+1-1,”), or other neume groupings, e.g. X, +3+1, -1-1, +3, 0 (this could represent, for example C, EF, ED, F, F or F, AB, AG, B, B).

### PR DESCRIPTION
**Pull request by notkaramel**
- Resolve #20 
- Adding a text box for user input
image
- Adding Regex to process user's input in 2 different mode:
  - Aquitanian notation ~ contour/pitch search, using numerical values (e.g., "1 2 -1")
  - Square notation ~ pitch search, using alphabetical representation (e.g., "A B A")
- Todo:
  - [x] Displaying a highlighted "custom" version of GABC underneath the text (MEI -> "custom" GABC). The highlighting should go on the pitches (or locs) rather than the syllables.
    It follows the structure of GABC with `syl_text(pitches_in_neume/pitches_in_neume)`, where the `/` divides the neumes within the syllable, and a regular space ` ` divides the words. For example: `Man(de)du(c)ca(d)ve(fg)runt(afga/ag) et(ga) sa(g)tu(fe)ra(fa)ti(g)` for the beginning of Chant 21.
  - [x] For Aquitanian, display in `loc` instead of `pitches_in_neume`. Example: `Man(12)du(3)...`
  - [x] For Square, use pitches.
  We are not using the "original" GABC as it encodes absolute positions with `a`, `b`, `c` rather than pitches, which are relative to the clef.

### CODE REVIEW

**Comment by martha-thomae** [comment]
After talking with Elsa, she likes the idea of highlighting the notes in the Verovio rendering too. So, for now we will have our "custom" GABC displayed on the table with the notes highlighted somehow, and also the actual notes highlighted in the Verovio rendering when clicking on "Display Chant."

**Comment by martha-thomae** [comment]
One question, in addition to the different font colors to distinguish the syllables with ornamental shapes, why did you use different types of underlines for the ornamental shapes?

I ask because Elsa was thinking that the underline could be used for the melodic search results instead, so I just wanted to clarify the reason why you have them in ornamental neumes (when they already use different font colors). Thank you, @notkaramel!

**Comment by notkaramel** [comment]
@martha-thomae I was thinking that changing the font colour alone is not enough in case a musicologist who uses the interface is colour-blind. It was also because when I prototyped it, different types of underlines was more detectable than the colour differences for me.

**Comment by martha-thomae** [comment]
> @martha-thomae I was thinking that changing the font colour alone is not enough in case a musicologist who uses the interface is colour-blind. It was also because when I prototyped it, different types of underlines were more detectable than the colour differences for me.

Yes, I thought that was why. And I think that this is great for accessibility purposes.

So, to summarize my conversation with Elsa this past Thursday, she wants:
1. To have the three types of queries you are implementing
2. To show more information about how the query is supposed to look (see previous comment) but to have that information in a separate place. Maybe instead of hovering and having that huge tooltip as we suggested before, we can use an ["information icon"](https://images.app.goo.gl/7AgXsHHmn7A8vLNS6) next to each of the three melodic search categories for people to click on and see the details mentioned in the comment above.
3. She wants the search results highlighted on Verovio (so, in each of the files when clicking on "Display Chant"). This is because Verovio is going to include some changes in the near future that will allow it to render things more accurately, so Elsa is fine with showing the highlighted results in Verovio now.
4. So, here is the point why I asked the question about why the ornamental neumes are shown by changing both the font colour and the font underline of the syllable: Elsa would like to highlight the syllable(s) of the melodic search by using underlines in the text (instead of what we talked about using some type of "custom GABC," she says it is enough to show results in the text itself). However, right now we are already using underline for ornamental neumes. She suggested just using colour for ornamental neumes and underlining for the melodic search results. But I also agree that using "colour + underline" for ornamental neumes is great for accessibility purposes (e.g., colour-blind people).

So, based on points 3 and 4, let's agree for now just to display the melodic search results in the Verovio rendering of the files (and I will check them one by one for now; it is fine). Then, we can re-evaluate how to show the melodic search results in the table itself. The important thing now is to implement it and show it somehow, then we can make it pretty.

**Comment by notkaramel** [comment]
Hi Martha @martha-thomae and Elsa @elsinhadl 

All features are implemented, please let me know how your meeting goes! I've tested with some use cases, but overall it seems to be working.

The highlight for melodic pattern at the moment is red dotted underline. This is temporary but it's doing its job. I will implement a better visual for all the types of highlighting ASAP (I am reading this [article](https://stackoverflow.com/questions/40861062/text-with-multiple-underlines) about **multiple underlines**, but that's just one idea).

---
The new interface would have the following elements:
- The search section:

image

- The result table (with the number of chants found and new highlighting)

image

- Information tab that explains the search modes. It might need some rewording

image

> **Absolute pitch (only for Square music script chants)**: Exact pitches could be (e.g., a b E F). Use uppercase letters for a lower octave and lowercase letters for an upper octave.
> 
> **Indefinite pitch (only for Aquitanian music script chants)**: The query indicates the note's location with reference to the line, which has a position of 0. Example: -2 -2 0 -1 0 +1. Here, the first note is two steps below the line (it can be either a major or minor third with respect to the line), the second note is the same as the first, the third note is on the line, the fourth note is one step below the line (either a semitone or tone), the fifth note is on the line, and the sixth note is one step above the line (either a semitone or tone). This will return similar results from the example given in the contour-based search.
> 
> **Contour (Melodic intervals)** in the form of positive or negative integers (e.g., +1 indicates one step up—either a semitone or a tone—from the previous note; 0 indicates unison; and -2 indicates two steps down—either a major or minor third—from the previous note). If looking for a series of notes, the integers should be separated by a space (e.g., 0 +2 -1 +1 +1).

- Highlight on the Verovio-rendered chant:

image

**Pull request merged**
